# Generated by Django 5.2.5 on 2026-02-19 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='balance',
        ),
    ]
