# Generated by Django 5.2.5 on 2025-12-10 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('c_idx', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=200)),
                ('c_yn', models.CharField(max_length=1)),
                ('c_number', models.CharField(max_length=50)),
                ('c_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='subject_db',
            fields=[
                ('s_idx', models.AutoField(primary_key=True, serialize=False)),
                ('s_gubun', models.CharField(max_length=1)),
                ('s_title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sum_total', models.IntegerField()),
                ('su_total', models.IntegerField()),
                ('etc_total', models.IntegerField()),
                ('s_date', models.DateField()),
                ('c_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.company_info')),
            ],
        ),
    ]
