# Generated by Django 5.2.5 on 2025-12-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='c_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
