# Generated by Django 5.2.5 on 2025-12-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0002_alter_company_info_c_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_db',
            name='c_idx',
        ),
        migrations.AddField(
            model_name='subject_db',
            name='c_idx',
            field=models.ManyToManyField(to='mt.company_info'),
        ),
    ]
