# Generated by Django 5.2.5 on 2025-12-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0003_remove_subject_db_c_idx_subject_db_c_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_db',
            name='c_idx',
        ),
        migrations.AddField(
            model_name='subject_db',
            name='c_idx',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mt.company_info'),
            preserve_default=False,
        ),
    ]
