# Generated by Django 5.2.5 on 2026-01-20 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0006_jik_gread_approve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gdraft_db',
            fields=[
                ('dr_idx', models.AutoField(primary_key=True, serialize=False)),
                ('dr_no', models.CharField(max_length=20, unique=True)),
                ('dr_date', models.DateField(auto_now_add=True)),
                ('dr_title', models.CharField(max_length=200)),
                ('dr_content', models.TextField()),
                ('dr_attachfile', models.FileField(blank=True, null=True, upload_to='gdraft/%Y/%m/%d/')),
                ('dr_indate', models.DateField(blank=True, null=True)),
                ('dr_save_status', models.CharField(choices=[('임시저장', '임시저장'), ('작성완료', '작성완료')], default='임시저장', max_length=10)),
                ('dr_status', models.CharField(choices=[('결재대기', '결재대기'), ('결재완료', '결재완료'), ('반려', '반려')], default='결재대기', max_length=10)),
                ('dr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gdraft_log',
            fields=[
                ('drl_idx', models.AutoField(primary_key=True, serialize=False)),
                ('drl_action', models.CharField(max_length=50)),
                ('drl_date', models.DateTimeField(auto_now_add=True)),
                ('dr_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdraft.gdraft_db')),
                ('drl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gdraft_status',
            fields=[
                ('drs_idx', models.AutoField(primary_key=True, serialize=False)),
                ('drs_status', models.CharField(choices=[('대기', '대기'), ('승인', '승인'), ('반려', '반려')], default='대기', max_length=10)),
                ('drs_date', models.DateField(blank=True, null=True)),
                ('drs_comment', models.TextField(blank=True, null=True)),
                ('dr_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdraft.gdraft_db')),
                ('drs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafter', to=settings.AUTH_USER_MODEL)),
                ('drs_jik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.jik_gread')),
            ],
        ),
    ]
