# Generated by Django 5.2.5 on 2026-01-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdraft_status',
            name='drs_jik',
            field=models.IntegerField(),
        ),
    ]
