# Generated by Django 5.2.5 on 2026-01-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdraft', '0002_alter_gdraft_status_drs_jik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdraft_db',
            name='dr_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
