# Generated by Django 5.2.5 on 2026-03-17 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='F_board',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_create_date', models.DateTimeField()),
                ('f_title', models.CharField(max_length=200)),
                ('f_contents', models.TextField()),
                ('f_file_one', models.FileField(blank=True, null=True, upload_to='f_files/')),
                ('f_file_two', models.FileField(blank=True, null=True, upload_to='f_files/')),
                ('f_file_three', models.FileField(blank=True, null=True, upload_to='f_files/')),
                ('f_cnt', models.IntegerField()),
                ('f_d_cnt', models.IntegerField()),
                ('f_yn', models.CharField(max_length=1)),
                ('f_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
