# Generated by Django 5.2.5 on 2026-03-17 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_board',
            name='f_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
