# Generated by Django 5.2.5 on 2026-01-06 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0006_jik_gread_approve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pc_secu_title_db',
            fields=[
                ('p_m_idx', models.AutoField(primary_key=True, serialize=False)),
                ('p_m_b', models.IntegerField()),
                ('p_m_m', models.IntegerField()),
                ('p_m_s', models.IntegerField()),
                ('p_m_title', models.CharField(max_length=400)),
                ('p_m_indate', models.DateTimeField()),
                ('p_m_YN', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='pc_secu_ck_db',
            fields=[
                ('p_m_c_idx', models.AutoField(primary_key=True, serialize=False)),
                ('p_m_c_val', models.IntegerField()),
                ('p_m_c_indate', models.DateTimeField()),
                ('p_m_c_wdate', models.DateTimeField(blank=True, null=True)),
                ('p_m_c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('p_m_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psecu.pc_secu_title_db')),
            ],
        ),
        migrations.CreateModel(
            name='pc_secu_cf_db',
            fields=[
                ('p_m_cf_idx', models.AutoField(primary_key=True, serialize=False)),
                ('p_m_cf_val', models.IntegerField()),
                ('p_m_cf_indate', models.DateTimeField()),
                ('p_m_cf_wdate', models.DateTimeField(blank=True, null=True)),
                ('p_m_c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('p_m_jik_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.jik_gread')),
                ('p_m_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psecu.pc_secu_title_db')),
            ],
        ),
    ]
