# Generated by Django 5.2.5 on 2026-01-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psecu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_secu_title_db',
            name='p_m_asc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
