# Generated by Django 5.2.5 on 2026-01-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psecu', '0002_pc_secu_title_db_p_m_asc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc_secu_ck_db',
            name='p_m_c_val',
            field=models.CharField(max_length=500),
        ),
    ]
