# Generated by Django 5.2.5 on 2026-01-09 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psecu', '0003_alter_pc_secu_ck_db_p_m_c_val'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_secu_ck_db',
            name='p_m_b',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='pc_work_board_db',
            fields=[
                ('p_wb_idx', models.AutoField(primary_key=True, serialize=False)),
                ('p_wb_b', models.IntegerField()),
                ('p_wb_indate', models.DateTimeField()),
                ('p_wb_wdate', models.DateTimeField(blank=True, null=True)),
                ('p_wb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
