# Generated by Django 5.2.5 on 2026-01-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psecu', '0004_pc_secu_ck_db_p_m_b_pc_work_board_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_work_board_db',
            name='p_wb_check',
            field=models.CharField(default='N', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc_work_board_db',
            name='p_wb_review_check',
            field=models.CharField(default='N', max_length=1),
            preserve_default=False,
        ),
    ]
