# Generated by Django 5.2.5 on 2026-01-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psecu', '0005_pc_work_board_db_p_wb_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_work_board_db',
            name='p_wb_check_userID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_work_board_db',
            name='p_wb_review_check_userID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
