# Generated by Django 5.2.5 on 2026-01-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psecu', '0006_pc_work_board_db_p_wb_check_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_secu_ck_db',
            name='p_wb_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
