# Generated by Django 5.2.4 on 2025-08-18 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_create_date', models.DateTimeField()),
                ('b_err_gubun', models.IntegerField()),
                ('b_subject', models.TextField()),
                ('b_contents', models.TextField()),
                ('b_link_one', models.TextField()),
                ('b_link_two', models.TextField()),
                ('b_file_one', models.FileField(upload_to='files/')),
                ('b_file_two', models.FileField(upload_to='files/')),
                ('b_file_three', models.FileField(upload_to='files/')),
                ('b_status', models.CharField()),
                ('b_cnt', models.IntegerField()),
                ('b_gubun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.category')),
                ('b_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
