# Generated by Django 5.2.4 on 2025-08-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='q_board',
            old_name='b_contents',
            new_name='b_content',
        ),
        migrations.AlterField(
            model_name='q_board',
            name='b_status',
            field=models.IntegerField(),
        ),
    ]
