# Generated by Django 5.2.4 on 2025-08-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_b_contents_q_board_b_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_board',
            name='b_file_one',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='q_board',
            name='b_file_three',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='q_board',
            name='b_file_two',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='q_board',
            name='b_link_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='q_board',
            name='b_link_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
