# Generated by Django 5.2.5 on 2025-08-25 01:44

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_q_board_b_file_one_alter_q_board_b_file_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_board',
            name='b_content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
