# Generated by Django 5.2.5 on 2025-08-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_q_board_b_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_board',
            name='b_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='q_board',
            name='b_link_one',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='q_board',
            name='b_link_two',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='q_board',
            name='b_subject',
            field=models.CharField(),
        ),
    ]
