# Generated by Django 5.2.5 on 2025-09-02 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_q_board_b_content_alter_q_board_b_link_one_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jik_gread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_gread', models.IntegerField()),
                ('j_name', models.CharField(max_length=50)),
                ('j_yn', models.CharField(max_length=1)),
                ('j_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_approve', models.CharField(max_length=1)),
                ('a_approve_date', models.DateTimeField(blank=True, null=True)),
                ('a_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.q_board')),
                ('a_jik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.jik_gread')),
            ],
        ),
    ]
